name: Deploy Go App to GitHub Pages

on:
  push:
    branches:
      - j-website
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Build Go application
        run: go build -o j-website

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: go-app
          path: j-website

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: go-app

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          build_dir: './static'